name: "fontc Font Compiler"
description: "Compile fonts from source files with the Rust fontc compiler."
inputs:
  source-path:
    description: "Path to the Designspace, UFO, or Glyphs source file"
    required: true
  args:
    description: "fontc command line arguments"
    required: false
    default: "none"
  version-tag:
    description: "fontc git version tag"
    required: false
    default: "none"
  branch:
    description: "fontc repository git branch HEAD commit"
    required: false
    default: "main"
  commit-sha:
    description: "fontc repository git commit SHA"
    required: false
    default: "none"

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: "type"
  color: "purple"
