name: "fontc Font Compiler"
description: "Compile fonts from source files with the Rust fontc compiler."
inputs:
  source-path:
    description: "Path to a Designspace, UFO, or Glyphs source file"
    required: true
  args:
    description: "fontc command line arguments"
    required: false
    default: "none"
  version-tag:
    description: "Use fontc at a repository git version tag"
    required: false
    default: "none"
  branch:
    description: "Use fontc built at a repository git branch HEAD commit"
    required: false
    default: "main"
  commit-sha:
    description: "Use fontc built at a repository git commit SHA"
    required: false
    default: "none"
  debug:
    description: "Use a debug build of the fontc compiler"
    required: false
    default: "false"

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: "type"
  color: "purple"
